version: '3.3'

services:
  wordpress:
    image: wordpress
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: admin  
      WORDPRESS_DB_PASSWORD: admin  
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql:8.0  
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: admin  
      MYSQL_PASSWORD: admin  
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  wordpress:
  db_data:
